<a href="https://colab.research.google.com/github/jeo2k1/numpy/blob/main/curso_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Libreria para Ciencia de Datos

In [130]:
import numpy as np

In [131]:
def crearArray(fila,columna):
  array = np.random.random((fila,columna))
  return array

In [132]:
array_1d=np.array([1,4,3])


In [133]:
array_1d

array([1, 4, 3])

In [134]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [135]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

# Creando Arrays

In [136]:
# de ceros con 3 filas 4 columnas
array_ceros=np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [137]:
# de unos con 2 dimensiones 4 filas y 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [138]:
# intervalos y saltos
np.arange(12,30,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [139]:
# intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [140]:
#Valor dado
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [141]:
#Matriz identidad, diagonal de unos
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [142]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.40045952, 0.58492886, 0.07857472, 0.39221227],
       [0.90823916, 0.12093105, 0.13832907, 0.34140105],
       [0.41351339, 0.71875747, 0.26244314, 0.06971535],
       [0.29203195, 0.01968527, 0.63303246, 0.46966406]])

In [143]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Grabar y cargar

In [144]:
#Grabar
#np.save('mi_array', np.random.random((3,3)))
np.save('mi_array_3d', array_3d)

In [145]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [146]:
#Grabar a fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [147]:
#Cargar de fichero de texto
array_2d=np.loadtxt('mi_array.txt')
array_2d

array([[1., 4., 2.],
       [5., 2., 3.]])

#Tipo de datos

In [148]:
#Entero
np.int64

numpy.int64

In [149]:
#Decimal, numero doble prescision o de punto flotante
np.float64

numpy.float64

In [150]:
#Complejos
np.complex_

numpy.complex128

In [151]:
#Booleanos
np.bool_

numpy.bool_

In [152]:
#Objetos
np.object_

numpy.object_

In [153]:
#Cadenas
np.string_

numpy.bytes_

In [154]:
np.unicode_

numpy.str_

#Propiedades y caracteristicas

In [155]:
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [156]:
#Dimension o forma
array_3d.shape

(3, 2, 3)

In [157]:
#Longitud
len(array_3d)

3

In [158]:
#Numero de dimensiones
array_3d.ndim

3

In [159]:
#Tamaño o numero de elementos
array_3d.size

18

In [160]:
#Tipo de datos en el array

In [161]:
array_3d.dtype

dtype('float64')

In [162]:
array_3d.dtype.name

'float64'

In [163]:
#Convertir de un tipo a otro
array_3d.astype(int)

array([[[1, 4, 2],
        [1, 5, 9]],

       [[7, 5, 9],
        [8, 1, 3]],

       [[3, 5, 3],
        [7, 2, 9]]])

#Ayuda

In [164]:
np.info(np.ndarray.dtype)

#Operadores Aritmeticos

In [165]:
#Arrays de ejemplos
array1=np.random.random((4,4))
array1

array([[0.0516591 , 0.41079755, 0.89730584, 0.79006363],
       [0.75936319, 0.89970564, 0.73565183, 0.36455734],
       [0.12670884, 0.95652558, 0.69782152, 0.80942821],
       [0.3660694 , 0.83425628, 0.31379682, 0.8971128 ]])

In [166]:
array2=np.random.random((4,4))
array2

array([[0.74688918, 0.94471894, 0.38126212, 0.40410015],
       [0.15417695, 0.39274965, 0.7823986 , 0.90555351],
       [0.42112443, 0.44125643, 0.11553128, 0.33626771],
       [0.00129791, 0.87751712, 0.03029084, 0.72801934]])

In [167]:
from numpy.core.arrayprint import array2string
#Suma
array3 = array1 + array2
array3

array([[0.79854828, 1.3555165 , 1.27856796, 1.19416378],
       [0.91354014, 1.29245528, 1.51805042, 1.27011084],
       [0.54783327, 1.397782  , 0.81335281, 1.14569592],
       [0.36736731, 1.7117734 , 0.34408766, 1.62513214]])

In [168]:
#Otra opcion de sumar
array3 = np.add(array1,array2)
array3

array([[0.79854828, 1.3555165 , 1.27856796, 1.19416378],
       [0.91354014, 1.29245528, 1.51805042, 1.27011084],
       [0.54783327, 1.397782  , 0.81335281, 1.14569592],
       [0.36736731, 1.7117734 , 0.34408766, 1.62513214]])

In [169]:
#Resta
array3 = array1 - array2
array3

array([[-0.69523007, -0.53392139,  0.51604371,  0.38596348],
       [ 0.60518624,  0.50695599, -0.04674677, -0.54099617],
       [-0.2944156 ,  0.51526915,  0.58229024,  0.4731605 ],
       [ 0.36477149, -0.04326085,  0.28350598,  0.16909347]])

In [170]:
#Multiplicacion
array3 = np.multiply(array1,array2)
array3

array([[3.85836265e-02, 3.88088231e-01, 3.42108727e-01, 3.19264829e-01],
       [1.17076302e-01, 3.53359072e-01, 5.75572957e-01, 3.30126175e-01],
       [5.33601861e-02, 4.22073057e-01, 8.06202164e-02, 2.72184569e-01],
       [4.75126009e-04, 7.32074168e-01, 9.50516862e-03, 6.53115469e-01]])

In [171]:
#Division
array3 = array1/array2
array3

array([[6.91656893e-02, 4.34835735e-01, 2.35351425e+00, 1.95511840e+00],
       [4.92527048e+00, 2.29078662e+00, 9.40251973e-01, 4.02579564e-01],
       [3.00882175e-01, 2.16773178e+00, 6.04010881e+00, 2.40709467e+00],
       [2.82044770e+02, 9.50700849e-01, 1.03594631e+01, 1.23226507e+00]])

In [172]:
#Otra forma de dividir
array3 = np.divide(array1,array2)
array3

array([[6.91656893e-02, 4.34835735e-01, 2.35351425e+00, 1.95511840e+00],
       [4.92527048e+00, 2.29078662e+00, 9.40251973e-01, 4.02579564e-01],
       [3.00882175e-01, 2.16773178e+00, 6.04010881e+00, 2.40709467e+00],
       [2.82044770e+02, 9.50700849e-01, 1.03594631e+01, 1.23226507e+00]])

In [173]:
#Exponencial
np.exp(array1)

array([[1.05301671, 1.50802003, 2.45298546, 2.20353663],
       [2.13691498, 2.4588792 , 2.08684181, 1.43987649],
       [1.13508647, 2.60263808, 2.00937057, 2.24662302],
       [1.44205532, 2.30310054, 1.36861163, 2.452512  ]])

In [174]:
#Seno
np.sin(array1)

array([[0.05163613, 0.39934066, 0.78164935, 0.71039806],
       [0.68845972, 0.7831439 , 0.67107056, 0.35653576],
       [0.12637005, 0.81719398, 0.64254997, 0.72389281],
       [0.35794804, 0.74079714, 0.30867227, 0.78152894]])

In [175]:
#Coseno
np.cos(array2)

array([[0.73380578, 0.58597065, 0.92819575, 0.91945658],
       [0.98813826, 0.92386018, 0.70922461, 0.61725019],
       [0.91262986, 0.90421579, 0.99333368, 0.94399277],
       [0.99999916, 0.63906283, 0.99954127, 0.74649378]])

In [176]:
#Logartimo
np.log(array2)

array([[-0.29183846, -0.05686781, -0.96426816, -0.90609254],
       [-1.8696543 , -0.9345829 , -0.24539095, -0.09920891],
       [-0.86482693, -0.81812911, -2.15821393, -1.08984769],
       [-6.64699816, -0.13065881, -3.49690999, -0.31742767]])

In [177]:
#Producto de matrices
array1.dot(array2)

array([[0.48082199, 1.29938026, 0.46870168, 1.2697912 ],
       [1.01614814, 1.71526026, 1.0894784 , 1.63437112],
       [0.53703192, 1.51358467, 0.90183203, 1.74132238],
       [0.53534824, 1.59918326, 0.85571698, 1.6620276 ]])

#Comparacion

==, !=, <, >, <=, >=, and, or

In [178]:
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [179]:
array1 < 0.5

array([[ True,  True, False, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False]])

In [180]:
array1

array([[0.0516591 , 0.41079755, 0.89730584, 0.79006363],
       [0.75936319, 0.89970564, 0.73565183, 0.36455734],
       [0.12670884, 0.95652558, 0.69782152, 0.80942821],
       [0.3660694 , 0.83425628, 0.31379682, 0.8971128 ]])

In [181]:
array3 <= 0.4

array([[ True, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False]])

In [182]:
array3

array([[6.91656893e-02, 4.34835735e-01, 2.35351425e+00, 1.95511840e+00],
       [4.92527048e+00, 2.29078662e+00, 9.40251973e-01, 4.02579564e-01],
       [3.00882175e-01, 2.16773178e+00, 6.04010881e+00, 2.40709467e+00],
       [2.82044770e+02, 9.50700849e-01, 1.03594631e+01, 1.23226507e+00]])

#Estadisticos basicos y otras funciones

In [183]:
array1=crearArray(5,5)
array1

array([[0.7245818 , 0.42574136, 0.33024122, 0.95489685, 0.89265206],
       [0.03381017, 0.9355068 , 0.61799311, 0.27648163, 0.80198138],
       [0.86034987, 0.06951677, 0.84627556, 0.76459001, 0.01423011],
       [0.38463683, 0.06685466, 0.7607356 , 0.24641941, 0.27144729],
       [0.58987176, 0.21113867, 0.75226173, 0.7945158 , 0.59924276]])

In [184]:
array1.sum()

13.225973189460083

In [185]:
array1.min()

0.014230105118209435

In [186]:
array1.max()

0.9548968522537947

In [187]:
#Maximo por filas
array1.max(axis=0)

array([0.86034987, 0.9355068 , 0.84627556, 0.95489685, 0.89265206])

In [188]:
#Maximo por columnas
array1.max(axis=1)

array([0.95489685, 0.9355068 , 0.86034987, 0.7607356 , 0.7945158 ])

In [189]:
#Suma acumulada
array1.cumsum(axis=1)

array([[0.7245818 , 1.15032316, 1.48056437, 2.43546122, 3.32811328],
       [0.03381017, 0.96931697, 1.58731008, 1.86379171, 2.66577309],
       [0.86034987, 0.92986664, 1.77614219, 2.5407322 , 2.55496231],
       [0.38463683, 0.45149149, 1.21222708, 1.4586465 , 1.73009379],
       [0.58987176, 0.80101043, 1.55327216, 2.34778796, 2.94703072]])

In [190]:
array1

array([[0.7245818 , 0.42574136, 0.33024122, 0.95489685, 0.89265206],
       [0.03381017, 0.9355068 , 0.61799311, 0.27648163, 0.80198138],
       [0.86034987, 0.06951677, 0.84627556, 0.76459001, 0.01423011],
       [0.38463683, 0.06685466, 0.7607356 , 0.24641941, 0.27144729],
       [0.58987176, 0.21113867, 0.75226173, 0.7945158 , 0.59924276]])

In [191]:
#Media
np.mean(array1)

0.5290389275784033

In [192]:
#Mediana
np.median(array1)

0.5992427553820356

In [193]:
#Correlacion
np.corrcoef(array1)

array([[ 1.        , -0.40438985, -0.05305966, -0.40267416,  0.38215205],
       [-0.40438985,  1.        , -0.81354619, -0.23585847, -0.54938212],
       [-0.05305966, -0.81354619,  1.        ,  0.64688097,  0.67903049],
       [-0.40267416, -0.23585847,  0.64688097,  1.        ,  0.63931781],
       [ 0.38215205, -0.54938212,  0.67903049,  0.63931781,  1.        ]])

In [194]:
#Desviacion
np.std(array1)

0.30757846336212114

#Copiando Array

In [195]:
array1 = np.random.randint(21,size=(4,4))
array1

array([[18, 11,  8, 13],
       [17,  4, 14,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [196]:
#Crea una imagen del array, el valor cambiado se refleja en los dos
array_cop=array1.view()
array_cop

array([[18, 11,  8, 13],
       [17,  4, 14,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [197]:
np.array_equal(array1,array_cop)

True

In [198]:
#Modifica un valor de la copia
array_cop[0,1] = 99
array_cop

array([[18, 99,  8, 13],
       [17,  4, 14,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [199]:
#Modificamos un valor original
array1[1,2] = 88
array1

array([[18, 99,  8, 13],
       [17,  4, 88,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [200]:
array_cop

array([[18, 99,  8, 13],
       [17,  4, 88,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [201]:
#Creamos copia independiente
array_cop2 = np.copy(array1)
array_cop2

array([[18, 99,  8, 13],
       [17,  4, 88,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [202]:
array_cop2[2,3] = 77
array_cop2

array([[18, 99,  8, 13],
       [17,  4, 88,  3],
       [ 2, 16,  2, 77],
       [ 0, 11,  3, 14]])

In [203]:
array1

array([[18, 99,  8, 13],
       [17,  4, 88,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [204]:
array_cop2 = array1 * 3
array_cop2

array([[ 54, 297,  24,  39],
       [ 51,  12, 264,   9],
       [  6,  48,   6,  60],
       [  0,  33,   9,  42]])

In [206]:
array_cop2 = array1.copy()
array_cop2

array([[18, 99,  8, 13],
       [17,  4, 88,  3],
       [ 2, 16,  2, 20],
       [ 0, 11,  3, 14]])

In [208]:
np.array_equal(array1,array_cop2)

True

#Arrays, ordenamiento

In [213]:
array_1 = np.random.randint(41,size=(10,10))
array_1

array([[ 3, 17, 26, 23, 15, 20, 33,  6, 28, 40],
       [34, 21, 19,  6, 39, 31, 23, 12, 22,  3],
       [28, 20, 38,  4, 25, 17,  4,  2, 17, 15],
       [23, 31, 26, 22, 38, 19, 16, 14,  9, 25],
       [ 3, 23,  6, 10, 23, 20, 33, 29, 17, 23],
       [34, 21, 39, 23, 20,  9,  2, 37, 31, 14],
       [35, 16, 32, 35, 39, 26, 26, 29, 21, 22],
       [40, 39, 18, 17,  5, 29, 38,  6, 36, 39],
       [30, 32,  7, 27,  0,  5, 21,  0,  9,  7],
       [36, 34,  2, 40, 18, 14, 19, 30, 22,  3]])

In [210]:
array_2 = np.random.randint(31,size=(10,10))
array_2

array([[16, 23,  7, 15,  7,  6, 15, 22, 14,  3],
       [27, 21, 28,  6, 14, 25, 27, 29, 26, 24],
       [ 8, 27, 11,  0, 29,  0, 23, 23, 16, 12],
       [12,  5, 11, 19, 15,  5, 23,  3, 27,  0],
       [15, 19,  8,  4, 12, 20, 26, 16,  9, 20],
       [27,  8, 16, 17,  7,  5, 11,  8,  9, 16],
       [12,  5, 10, 17,  7, 28, 25, 24, 16, 17],
       [ 1,  3, 16, 20, 30,  2, 26,  3, 16, 28],
       [ 2,  2,  7,  2, 10, 19, 12, 20, 12, 21],
       [12,  3, 26, 11, 18, 16,  6,  6,  2, 15]])

In [211]:
array_1

array([[ 9, 13, 14,  5, 27, 39,  4, 18, 22, 38],
       [12,  8, 33,  2, 38, 19, 31,  5, 15, 31],
       [25, 39, 15, 37,  6, 15, 11, 31,  9,  4],
       [15, 10, 39, 26, 40,  6, 12, 25, 11,  1],
       [26, 33, 15, 35, 13,  2,  4, 17,  0, 32],
       [18, 13, 14, 38, 17, 27, 39, 40, 23,  5],
       [38,  3, 29, 31, 16,  2, 13,  6,  5, 12],
       [ 3,  4, 23, 39,  1,  6, 34, 38, 37, 16],
       [28, 18, 28, 16, 12, 16, 15, 27, 38, 38],
       [ 5,  6, 11, 29, 31, 30, 35, 14,  1, 28]])

In [212]:
array_1.sort()
array_1

array([[ 4,  5,  9, 13, 14, 18, 22, 27, 38, 39],
       [ 2,  5,  8, 12, 15, 19, 31, 31, 33, 38],
       [ 4,  6,  9, 11, 15, 15, 25, 31, 37, 39],
       [ 1,  6, 10, 11, 12, 15, 25, 26, 39, 40],
       [ 0,  2,  4, 13, 15, 17, 26, 32, 33, 35],
       [ 5, 13, 14, 17, 18, 23, 27, 38, 39, 40],
       [ 2,  3,  5,  6, 12, 13, 16, 29, 31, 38],
       [ 1,  3,  4,  6, 16, 23, 34, 37, 38, 39],
       [12, 15, 16, 16, 18, 27, 28, 28, 38, 38],
       [ 1,  5,  6, 11, 14, 28, 29, 30, 31, 35]])

In [214]:
#Ordena por fila
array_1.sort(axis=1)
array_1

array([[ 3,  6, 15, 17, 20, 23, 26, 28, 33, 40],
       [ 3,  6, 12, 19, 21, 22, 23, 31, 34, 39],
       [ 2,  4,  4, 15, 17, 17, 20, 25, 28, 38],
       [ 9, 14, 16, 19, 22, 23, 25, 26, 31, 38],
       [ 3,  6, 10, 17, 20, 23, 23, 23, 29, 33],
       [ 2,  9, 14, 20, 21, 23, 31, 34, 37, 39],
       [16, 21, 22, 26, 26, 29, 32, 35, 35, 39],
       [ 5,  6, 17, 18, 29, 36, 38, 39, 39, 40],
       [ 0,  0,  5,  7,  7,  9, 21, 27, 30, 32],
       [ 2,  3, 14, 18, 19, 22, 30, 34, 36, 40]])

In [216]:
#Ordena por columna
array_2.sort(axis=0)
array_2

array([[ 1,  2,  7,  0,  7,  0,  6,  3,  2,  0],
       [ 2,  3,  7,  2,  7,  2, 11,  3,  9,  3],
       [ 8,  3,  8,  4,  7,  5, 12,  6,  9, 12],
       [12,  5, 10,  6, 10,  5, 15,  8, 12, 15],
       [12,  5, 11, 11, 12,  6, 23, 16, 14, 16],
       [12,  8, 11, 15, 14, 16, 23, 20, 16, 17],
       [15, 19, 16, 17, 15, 19, 25, 22, 16, 20],
       [16, 21, 16, 17, 18, 20, 26, 23, 16, 21],
       [27, 23, 26, 19, 29, 25, 26, 24, 26, 24],
       [27, 27, 28, 20, 30, 28, 27, 29, 27, 28]])