<a href="https://colab.research.google.com/github/jeo2k1/numpy/blob/main/curso_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Libreria para Ciencia de Datos

In [1]:
import numpy as np

In [2]:
array_1d=np.array([1,4,3])


In [3]:
array_1d

array([1, 4, 3])

In [4]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [5]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

# Creando Arrays

In [6]:
# de ceros con 3 filas 4 columnas
array_ceros=np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
# de unos con 2 dimensiones 4 filas y 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [8]:
# intervalos y saltos
np.arange(12,30,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
# intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [10]:
#Valor dado
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [11]:
#Matriz identidad, diagonal de unos
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.81772494, 0.97006524, 0.17253514, 0.18918618],
       [0.31868845, 0.75439197, 0.00278827, 0.58939745],
       [0.33164112, 0.07180006, 0.65633579, 0.86018637],
       [0.23756267, 0.21832474, 0.08287368, 0.43434594]])

In [13]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Grabar y cargar

In [14]:
#Grabar
#np.save('mi_array', np.random.random((3,3)))
np.save('mi_array_3d', array_3d)

In [15]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [16]:
#Grabar a fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [17]:
#Cargar de fichero de texto
array_2d=np.loadtxt('mi_array.txt')
array_2d

array([[1., 4., 2.],
       [5., 2., 3.]])

#Tipo de datos

In [18]:
#Entero
np.int64

numpy.int64

In [19]:
#Decimal, numero doble prescision o de punto flotante
np.float64

numpy.float64

In [20]:
#Complejos
np.complex_

numpy.complex128

In [21]:
#Booleanos
np.bool_

numpy.bool_

In [22]:
#Objetos
np.object_

numpy.object_

In [23]:
#Cadenas
np.string_

numpy.bytes_

In [24]:
np.unicode_

numpy.str_

#Propiedades y caracteristicas

In [25]:
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [26]:
#Dimension o forma
array_3d.shape

(3, 2, 3)

In [27]:
#Longitud
len(array_3d)

3

In [28]:
#Numero de dimensiones
array_3d.ndim

3

In [29]:
#Tamaño o numero de elementos
array_3d.size

18

In [30]:
#Tipo de datos en el array

In [31]:
array_3d.dtype

dtype('float64')

In [32]:
array_3d.dtype.name

'float64'

In [33]:
#Convertir de un tipo a otro
array_3d.astype(int)

array([[[1, 4, 2],
        [1, 5, 9]],

       [[7, 5, 9],
        [8, 1, 3]],

       [[3, 5, 3],
        [7, 2, 9]]])

#Ayuda

In [34]:
np.info(np.ndarray.dtype)

In [34]:
#