<a href="https://colab.research.google.com/github/jeo2k1/numpy/blob/main/curso_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Libreria para Ciencia de Datos

In [1]:
import numpy as np

In [2]:
def crearArray(fila,columna):
  array = np.random.random((fila,columna))
  return array

In [3]:
array_1d=np.array([1,4,3])


In [4]:
array_1d

array([1, 4, 3])

In [5]:
array_2d=np.array([(1,4,2),(5,2,3)])
array_2d

array([[1, 4, 2],
       [5, 2, 3]])

In [6]:
array_3d=np.array([[(1.6,4.5,2),(1,5.8,9)],[(7,5,9.3),(8,1.4,3)],[(3,5,3),(7,2,9)]],dtype=float)
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

# Creando Arrays

In [7]:
# de ceros con 3 filas 4 columnas
array_ceros=np.zeros((3,4))
array_ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# de unos con 2 dimensiones 4 filas y 5 columnas
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [9]:
# intervalos y saltos
np.arange(12,30,2)

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
# intervalo y divisiones
np.linspace(0,4,7)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        ])

In [11]:
#Valor dado
np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [12]:
#Matriz identidad, diagonal de unos
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#Valores aleatorios entre 0 y 1
np.random.random((4,4))

array([[0.66614242, 0.81201649, 0.19541294, 0.90193558],
       [0.15066015, 0.80954992, 0.3134563 , 0.17126769],
       [0.30757244, 0.4410716 , 0.45596579, 0.20707935],
       [0.39602921, 0.93166394, 0.58385605, 0.65892513]])

In [14]:
#Vacio de 4 filas y 3 columnas
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#Grabar y cargar

In [15]:
#Grabar
#np.save('mi_array', np.random.random((3,3)))
np.save('mi_array_3d', array_3d)

In [16]:
#Cargar
mi_array=np.load('mi_array_3d.npy')
mi_array

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [17]:
#Grabar a fichero de texto
np.savetxt('mi_array.txt',array_2d,delimiter=" ")

In [18]:
#Cargar de fichero de texto
array_2d=np.loadtxt('mi_array.txt')
array_2d

array([[1., 4., 2.],
       [5., 2., 3.]])

#Tipo de datos

In [19]:
#Entero
np.int64

numpy.int64

In [20]:
#Decimal, numero doble prescision o de punto flotante
np.float64

numpy.float64

In [21]:
#Complejos
np.complex_

numpy.complex128

In [22]:
#Booleanos
np.bool_

numpy.bool_

In [23]:
#Objetos
np.object_

numpy.object_

In [24]:
#Cadenas
np.string_

numpy.bytes_

In [25]:
np.unicode_

numpy.str_

#Propiedades y caracteristicas

In [26]:
array_3d

array([[[1.6, 4.5, 2. ],
        [1. , 5.8, 9. ]],

       [[7. , 5. , 9.3],
        [8. , 1.4, 3. ]],

       [[3. , 5. , 3. ],
        [7. , 2. , 9. ]]])

In [27]:
#Dimension o forma
array_3d.shape

(3, 2, 3)

In [28]:
#Longitud
len(array_3d)

3

In [29]:
#Numero de dimensiones
array_3d.ndim

3

In [30]:
#Tamaño o numero de elementos
array_3d.size

18

In [31]:
#Tipo de datos en el array

In [32]:
array_3d.dtype

dtype('float64')

In [33]:
array_3d.dtype.name

'float64'

In [34]:
#Convertir de un tipo a otro
array_3d.astype(int)

array([[[1, 4, 2],
        [1, 5, 9]],

       [[7, 5, 9],
        [8, 1, 3]],

       [[3, 5, 3],
        [7, 2, 9]]])

#Ayuda

In [35]:
np.info(np.ndarray.dtype)

#Operadores Aritmeticos

In [36]:
#Arrays de ejemplos
array1=np.random.random((4,4))
array1

array([[0.39775752, 0.02126087, 0.72544555, 0.37098724],
       [0.96398912, 0.25864098, 0.69644857, 0.56048177],
       [0.98976826, 0.9261329 , 0.22789837, 0.7931245 ],
       [0.28016281, 0.54308641, 0.36529116, 0.05838893]])

In [37]:
array2=np.random.random((4,4))
array2

array([[0.64555423, 0.77765045, 0.27773173, 0.85630742],
       [0.39345136, 0.08688182, 0.75174338, 0.02057475],
       [0.48204399, 0.25265876, 0.35079332, 0.81730467],
       [0.24917236, 0.38959481, 0.32989091, 0.97301296]])

In [38]:
from numpy.core.arrayprint import array2string
#Suma
array3 = array1 + array2
array3

array([[1.04331175, 0.79891132, 1.00317728, 1.22729466],
       [1.35744047, 0.3455228 , 1.44819195, 0.58105651],
       [1.47181224, 1.17879165, 0.57869168, 1.61042917],
       [0.52933517, 0.93268122, 0.69518208, 1.03140188]])

In [39]:
#Otra opcion de sumar
array3 = np.add(array1,array2)
array3

array([[1.04331175, 0.79891132, 1.00317728, 1.22729466],
       [1.35744047, 0.3455228 , 1.44819195, 0.58105651],
       [1.47181224, 1.17879165, 0.57869168, 1.61042917],
       [0.52933517, 0.93268122, 0.69518208, 1.03140188]])

In [40]:
#Resta
array3 = array1 - array2
array3

array([[-0.24779671, -0.75638958,  0.44771382, -0.48532019],
       [ 0.57053776,  0.17175915, -0.05529482,  0.53990702],
       [ 0.50772427,  0.67347414, -0.12289495, -0.02418016],
       [ 0.03099045,  0.1534916 ,  0.03540025, -0.91462403]])

In [41]:
#Multiplicacion
array3 = np.multiply(array1,array2)
array3

array([[0.25677405, 0.01653352, 0.20147925, 0.31767912],
       [0.37928282, 0.0224712 , 0.5235506 , 0.01153177],
       [0.47711184, 0.23399559, 0.07994522, 0.64822436],
       [0.06980883, 0.21158365, 0.12050624, 0.05681318]])

In [42]:
#Division
array3 = array1/array2
array3

array([[ 0.61614889,  0.02733988,  2.61203697,  0.43324071],
       [ 2.45008462,  2.97692849,  0.92644456, 27.24124937],
       [ 2.05327374,  3.66554835,  0.64966565,  0.97041475],
       [ 1.12437357,  1.39397752,  1.10730895,  0.06000838]])

In [43]:
#Otra forma de dividir
array3 = np.divide(array1,array2)
array3

array([[ 0.61614889,  0.02733988,  2.61203697,  0.43324071],
       [ 2.45008462,  2.97692849,  0.92644456, 27.24124937],
       [ 2.05327374,  3.66554835,  0.64966565,  0.97041475],
       [ 1.12437357,  1.39397752,  1.10730895,  0.06000838]])

In [44]:
#Exponencial
np.exp(array1)

array([[1.48848306, 1.02148849, 2.06565125, 1.44916458],
       [2.62213564, 1.29516873, 2.00661368, 1.75151612],
       [2.69061087, 2.52472689, 1.25595767, 2.21029171],
       [1.32334525, 1.72131135, 1.44093349, 1.06012723]])

In [45]:
#Seno
np.sin(array1)

array([[0.38735191, 0.02125927, 0.66346887, 0.36253568],
       [0.82147288, 0.25576697, 0.64149734, 0.53159432],
       [0.8358988 , 0.79930207, 0.22593073, 0.71254897],
       [0.27651211, 0.51678078, 0.35722126, 0.05835576]])

In [46]:
#Coseno
np.cos(array2)

array([[0.79876644, 0.71256397, 0.96167981, 0.65523141],
       [0.92359139, 0.99622815, 0.7304994 , 0.99978835],
       [0.8860492 , 0.96825121, 0.93910039, 0.68418941],
       [0.96911685, 0.92506303, 0.94607769, 0.56281162]])

In [47]:
#Logartimo
np.log(array2)

array([[-0.43764606, -0.25147815, -1.28109963, -0.15512583],
       [-0.93279784, -2.44320643, -0.28536026, -3.88369091],
       [-0.72971991, -1.37571548, -1.04755807, -0.20174334],
       [-1.38961043, -0.94264802, -1.10899324, -0.02735788]])

In [48]:
#Producto de matrices
array1.dot(array2)

array([[0.7072756 , 0.63898837, 0.50331937, 1.29492558],
       [1.1994453 , 1.16644239, 0.89136935, 1.94535919],
       [1.31081907, 1.21673556, 1.31269412, 1.82458367],
       [0.58517369, 0.38009511, 0.63347539, 0.60644671]])

#Comparacion

==, !=, <, >, <=, >=, and, or

In [49]:
array1==array2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [50]:
array1 < 0.5

array([[ True,  True, False,  True],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True, False,  True,  True]])

In [51]:
array1

array([[0.39775752, 0.02126087, 0.72544555, 0.37098724],
       [0.96398912, 0.25864098, 0.69644857, 0.56048177],
       [0.98976826, 0.9261329 , 0.22789837, 0.7931245 ],
       [0.28016281, 0.54308641, 0.36529116, 0.05838893]])

In [52]:
array3 <= 0.4

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [53]:
array3

array([[ 0.61614889,  0.02733988,  2.61203697,  0.43324071],
       [ 2.45008462,  2.97692849,  0.92644456, 27.24124937],
       [ 2.05327374,  3.66554835,  0.64966565,  0.97041475],
       [ 1.12437357,  1.39397752,  1.10730895,  0.06000838]])

#Estadisticos basicos y otras funciones

In [54]:
array1=crearArray(5,5)
array1

array([[0.87280782, 0.06244201, 0.5566793 , 0.44997479, 0.22360765],
       [0.16622258, 0.69240552, 0.21694646, 0.32998543, 0.73664701],
       [0.48637432, 0.62058034, 0.08063531, 0.42448348, 0.72160455],
       [0.60334007, 0.49668613, 0.43519035, 0.8846611 , 0.63617935],
       [0.08733821, 0.97251965, 0.26841891, 0.02167597, 0.3733953 ]])

In [55]:
array1.sum()

11.420801599042168

In [56]:
array1.min()

0.021675968053187833

In [57]:
array1.max()

0.9725196502034582

In [58]:
#Maximo por filas
array1.max(axis=0)

array([0.87280782, 0.97251965, 0.5566793 , 0.8846611 , 0.73664701])

In [59]:
#Maximo por columnas
array1.max(axis=1)

array([0.87280782, 0.73664701, 0.72160455, 0.8846611 , 0.97251965])

In [60]:
#Suma acumulada
array1.cumsum(axis=1)

array([[0.87280782, 0.93524984, 1.49192913, 1.94190392, 2.16551157],
       [0.16622258, 0.8586281 , 1.07557456, 1.40555999, 2.142207  ],
       [0.48637432, 1.10695465, 1.18758996, 1.61207344, 2.33367799],
       [0.60334007, 1.1000262 , 1.53521655, 2.41987765, 3.056057  ],
       [0.08733821, 1.05985786, 1.32827677, 1.34995274, 1.72334804]])

In [61]:
array1

array([[0.87280782, 0.06244201, 0.5566793 , 0.44997479, 0.22360765],
       [0.16622258, 0.69240552, 0.21694646, 0.32998543, 0.73664701],
       [0.48637432, 0.62058034, 0.08063531, 0.42448348, 0.72160455],
       [0.60334007, 0.49668613, 0.43519035, 0.8846611 , 0.63617935],
       [0.08733821, 0.97251965, 0.26841891, 0.02167597, 0.3733953 ]])

In [62]:
#Media
np.mean(array1)

0.45683206396168674

In [63]:
#Mediana
np.median(array1)

0.4499747893042213

In [64]:
#Correlacion
np.corrcoef(array1)

array([[ 1.        , -0.91160227, -0.49099487,  0.07694961, -0.77676563],
       [-0.91160227,  1.        ,  0.76048225, -0.05480187,  0.71504622],
       [-0.49099487,  0.76048225,  1.        ,  0.26571168,  0.38341951],
       [ 0.07694961, -0.05480187,  0.26571168,  1.        , -0.55118477],
       [-0.77676563,  0.71504622,  0.38341951, -0.55118477,  1.        ]])

In [65]:
#Desviacion
np.std(array1)

0.26819670194468026

#Copiando Array

In [66]:
array1 = np.random.randint(21,size=(4,4))
array1

array([[ 7,  9, 17, 17],
       [19,  7, 10, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [67]:
#Crea una imagen del array, el valor cambiado se refleja en los dos
array_cop=array1.view()
array_cop

array([[ 7,  9, 17, 17],
       [19,  7, 10, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [68]:
np.array_equal(array1,array_cop)

True

In [69]:
#Modifica un valor de la copia
array_cop[0,1] = 99
array_cop

array([[ 7, 99, 17, 17],
       [19,  7, 10, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [70]:
#Modificamos un valor original
array1[1,2] = 88
array1

array([[ 7, 99, 17, 17],
       [19,  7, 88, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [71]:
array_cop

array([[ 7, 99, 17, 17],
       [19,  7, 88, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [72]:
#Creamos copia independiente
array_cop2 = np.copy(array1)
array_cop2

array([[ 7, 99, 17, 17],
       [19,  7, 88, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [73]:
array_cop2[2,3] = 77
array_cop2

array([[ 7, 99, 17, 17],
       [19,  7, 88, 10],
       [16,  4,  3, 77],
       [ 6, 11,  4, 19]])

In [74]:
array1

array([[ 7, 99, 17, 17],
       [19,  7, 88, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [75]:
array_cop2 = array1 * 3
array_cop2

array([[ 21, 297,  51,  51],
       [ 57,  21, 264,  30],
       [ 48,  12,   9,  33],
       [ 18,  33,  12,  57]])

In [76]:
array_cop2 = array1.copy()
array_cop2

array([[ 7, 99, 17, 17],
       [19,  7, 88, 10],
       [16,  4,  3, 11],
       [ 6, 11,  4, 19]])

In [77]:
np.array_equal(array1,array_cop2)

True

#Arrays, ordenamiento

In [78]:
array_1 = np.random.randint(41,size=(10,10))
array_1

array([[12, 10,  3, 30, 22,  7, 37,  7, 15, 23],
       [14, 39,  9,  1,  5, 10,  2, 23, 25, 15],
       [20,  3, 40, 34, 20,  4, 12, 32, 15, 40],
       [13, 38, 18, 22, 24, 35, 36,  9, 32, 17],
       [35, 32, 28, 19, 11, 18, 15, 19, 15, 40],
       [25, 26,  2,  6,  5, 40,  7, 30, 31,  6],
       [25, 12, 21,  8, 13, 15, 25,  9, 20, 16],
       [29,  7, 22, 33, 23, 29, 39, 28, 32,  2],
       [ 7,  7, 39,  8, 37, 34, 39, 38,  7, 25],
       [38, 39, 38, 38, 26,  8, 37,  6,  6, 13]])

In [79]:
array_2 = np.random.randint(31,size=(10,10))
array_2

array([[14, 17, 30, 13, 10, 11,  3, 26, 12, 23],
       [ 0,  5, 25,  0,  3, 27, 27,  2, 24, 11],
       [11, 11, 23, 14, 17, 20, 17,  3, 25, 11],
       [24, 30,  4, 11,  4,  3, 12,  0,  3, 16],
       [20, 12, 11,  7, 19,  6,  9,  6, 11,  3],
       [10,  3, 14,  9, 19, 10, 28,  4, 20, 29],
       [18, 26, 29, 13, 11, 12, 28, 16, 12,  0],
       [ 4, 14, 13,  4,  4, 28, 12, 27, 22, 23],
       [30, 29,  8,  7, 13, 13,  8, 15,  8,  8],
       [26,  6, 17,  4,  5, 25, 17, 13, 26, 24]])

In [80]:
array_1

array([[12, 10,  3, 30, 22,  7, 37,  7, 15, 23],
       [14, 39,  9,  1,  5, 10,  2, 23, 25, 15],
       [20,  3, 40, 34, 20,  4, 12, 32, 15, 40],
       [13, 38, 18, 22, 24, 35, 36,  9, 32, 17],
       [35, 32, 28, 19, 11, 18, 15, 19, 15, 40],
       [25, 26,  2,  6,  5, 40,  7, 30, 31,  6],
       [25, 12, 21,  8, 13, 15, 25,  9, 20, 16],
       [29,  7, 22, 33, 23, 29, 39, 28, 32,  2],
       [ 7,  7, 39,  8, 37, 34, 39, 38,  7, 25],
       [38, 39, 38, 38, 26,  8, 37,  6,  6, 13]])

In [81]:
array_1.sort()
array_1

array([[ 3,  7,  7, 10, 12, 15, 22, 23, 30, 37],
       [ 1,  2,  5,  9, 10, 14, 15, 23, 25, 39],
       [ 3,  4, 12, 15, 20, 20, 32, 34, 40, 40],
       [ 9, 13, 17, 18, 22, 24, 32, 35, 36, 38],
       [11, 15, 15, 18, 19, 19, 28, 32, 35, 40],
       [ 2,  5,  6,  6,  7, 25, 26, 30, 31, 40],
       [ 8,  9, 12, 13, 15, 16, 20, 21, 25, 25],
       [ 2,  7, 22, 23, 28, 29, 29, 32, 33, 39],
       [ 7,  7,  7,  8, 25, 34, 37, 38, 39, 39],
       [ 6,  6,  8, 13, 26, 37, 38, 38, 38, 39]])

In [82]:
#Ordena por fila
array_1.sort(axis=1)
array_1

array([[ 3,  7,  7, 10, 12, 15, 22, 23, 30, 37],
       [ 1,  2,  5,  9, 10, 14, 15, 23, 25, 39],
       [ 3,  4, 12, 15, 20, 20, 32, 34, 40, 40],
       [ 9, 13, 17, 18, 22, 24, 32, 35, 36, 38],
       [11, 15, 15, 18, 19, 19, 28, 32, 35, 40],
       [ 2,  5,  6,  6,  7, 25, 26, 30, 31, 40],
       [ 8,  9, 12, 13, 15, 16, 20, 21, 25, 25],
       [ 2,  7, 22, 23, 28, 29, 29, 32, 33, 39],
       [ 7,  7,  7,  8, 25, 34, 37, 38, 39, 39],
       [ 6,  6,  8, 13, 26, 37, 38, 38, 38, 39]])

In [83]:
#Ordena por columna
array_2.sort(axis=0)
array_2

array([[ 0,  3,  4,  0,  3,  3,  3,  0,  3,  0],
       [ 4,  5,  8,  4,  4,  6,  8,  2,  8,  3],
       [10,  6, 11,  4,  4, 10,  9,  3, 11,  8],
       [11, 11, 13,  7,  5, 11, 12,  4, 12, 11],
       [14, 12, 14,  7, 10, 12, 12,  6, 12, 11],
       [18, 14, 17,  9, 11, 13, 17, 13, 20, 16],
       [20, 17, 23, 11, 13, 20, 17, 15, 22, 23],
       [24, 26, 25, 13, 17, 25, 27, 16, 24, 23],
       [26, 29, 29, 13, 19, 27, 28, 26, 25, 24],
       [30, 30, 30, 14, 19, 28, 28, 27, 26, 29]])

#

In [84]:
#Subconjuntos, indexado

In [85]:
array = np.random.randint(31,size=(10,10))
array

array([[16,  4, 25, 21, 26,  5, 28,  7, 17, 19],
       [21, 11, 29, 16, 23, 18, 29, 15, 16,  5],
       [24, 23, 12,  9,  0,  1, 23, 21, 27, 25],
       [23,  0, 11, 30, 22,  6, 24, 10, 18,  8],
       [29, 23, 10, 13, 11, 27, 27, 13, 12, 17],
       [30, 26, 11, 19, 14,  9,  4, 15, 27,  6],
       [28,  3,  1, 11,  4,  2,  1,  5, 28, 16],
       [29, 15, 21, 13,  2,  6, 17,  7, 13, 17],
       [26, 14,  2, 10,  4, 22,  2,  9, 17, 23],
       [ 1, 30, 28,  8,  8, 11,  3, 23, 20,  3]])

In [86]:
#Seleccionamos elementos de la fila 2, columna 3
array[2,3]

9

In [87]:
#Slicing
array[1:4]

array([[21, 11, 29, 16, 23, 18, 29, 15, 16,  5],
       [24, 23, 12,  9,  0,  1, 23, 21, 27, 25],
       [23,  0, 11, 30, 22,  6, 24, 10, 18,  8]])

In [88]:
array[1:4,5]

array([18,  1,  6])

In [89]:
array[:1]

array([[16,  4, 25, 21, 26,  5, 28,  7, 17, 19]])

In [90]:
array[3:4]

array([[23,  0, 11, 30, 22,  6, 24, 10, 18,  8]])

In [91]:
array[1:4,2:5]

array([[29, 16, 23],
       [12,  9,  0],
       [11, 30, 22]])

In [92]:
array

array([[16,  4, 25, 21, 26,  5, 28,  7, 17, 19],
       [21, 11, 29, 16, 23, 18, 29, 15, 16,  5],
       [24, 23, 12,  9,  0,  1, 23, 21, 27, 25],
       [23,  0, 11, 30, 22,  6, 24, 10, 18,  8],
       [29, 23, 10, 13, 11, 27, 27, 13, 12, 17],
       [30, 26, 11, 19, 14,  9,  4, 15, 27,  6],
       [28,  3,  1, 11,  4,  2,  1,  5, 28, 16],
       [29, 15, 21, 13,  2,  6, 17,  7, 13, 17],
       [26, 14,  2, 10,  4, 22,  2,  9, 17, 23],
       [ 1, 30, 28,  8,  8, 11,  3, 23, 20,  3]])

In [93]:
array[::-1]

array([[ 1, 30, 28,  8,  8, 11,  3, 23, 20,  3],
       [26, 14,  2, 10,  4, 22,  2,  9, 17, 23],
       [29, 15, 21, 13,  2,  6, 17,  7, 13, 17],
       [28,  3,  1, 11,  4,  2,  1,  5, 28, 16],
       [30, 26, 11, 19, 14,  9,  4, 15, 27,  6],
       [29, 23, 10, 13, 11, 27, 27, 13, 12, 17],
       [23,  0, 11, 30, 22,  6, 24, 10, 18,  8],
       [24, 23, 12,  9,  0,  1, 23, 21, 27, 25],
       [21, 11, 29, 16, 23, 18, 29, 15, 16,  5],
       [16,  4, 25, 21, 26,  5, 28,  7, 17, 19]])

#Manipulacion de arrays

In [94]:
array=np.random.randint(10,size=(5,5))
array

array([[4, 8, 2, 7, 7],
       [5, 7, 2, 2, 5],
       [9, 4, 4, 4, 0],
       [4, 1, 1, 9, 7],
       [2, 0, 9, 4, 4]])

In [95]:
#Traspuesta
array_t=np.transpose(array)
array_t

array([[4, 5, 9, 4, 2],
       [8, 7, 4, 1, 0],
       [2, 2, 4, 1, 9],
       [7, 2, 4, 9, 4],
       [7, 5, 0, 7, 4]])

In [96]:
#Aplanar el array en una fila
array.ravel()

array([4, 8, 2, 7, 7, 5, 7, 2, 2, 5, 9, 4, 4, 4, 0, 4, 1, 1, 9, 7, 2, 0,
       9, 4, 4])

In [97]:
#Cambiamos la forma del arreglo pero no los datos
array.reshape(5,5)

array([[4, 8, 2, 7, 7],
       [5, 7, 2, 2, 5],
       [9, 4, 4, 4, 0],
       [4, 1, 1, 9, 7],
       [2, 0, 9, 4, 4]])

In [98]:
array.reshape(25,1)

array([[4],
       [8],
       [2],
       [7],
       [7],
       [5],
       [7],
       [2],
       [2],
       [5],
       [9],
       [4],
       [4],
       [4],
       [0],
       [4],
       [1],
       [1],
       [9],
       [7],
       [2],
       [0],
       [9],
       [4],
       [4]])

In [99]:
array=np.random.randint(10,size=(4,24))
array

array([[8, 2, 6, 3, 8, 3, 6, 7, 2, 2, 1, 9, 3, 3, 9, 5, 2, 4, 8, 5, 8, 1,
        1, 6],
       [9, 2, 3, 6, 0, 3, 5, 8, 3, 6, 6, 7, 8, 4, 6, 5, 1, 1, 8, 5, 7, 6,
        2, 7],
       [7, 2, 9, 7, 5, 3, 1, 0, 8, 5, 9, 1, 1, 4, 1, 5, 8, 5, 3, 6, 3, 7,
        1, 1],
       [8, 2, 5, 2, 4, 9, 1, 2, 9, 9, 5, 5, 5, 3, 0, 0, 2, 5, 6, 1, 7, 6,
        3, 5]])

In [100]:
array.reshape(12,8)

array([[8, 2, 6, 3, 8, 3, 6, 7],
       [2, 2, 1, 9, 3, 3, 9, 5],
       [2, 4, 8, 5, 8, 1, 1, 6],
       [9, 2, 3, 6, 0, 3, 5, 8],
       [3, 6, 6, 7, 8, 4, 6, 5],
       [1, 1, 8, 5, 7, 6, 2, 7],
       [7, 2, 9, 7, 5, 3, 1, 0],
       [8, 5, 9, 1, 1, 4, 1, 5],
       [8, 5, 3, 6, 3, 7, 1, 1],
       [8, 2, 5, 2, 4, 9, 1, 2],
       [9, 9, 5, 5, 5, 3, 0, 0],
       [2, 5, 6, 1, 7, 6, 3, 5]])

In [101]:
#Otra forma
array.resize((8,12))
array

array([[8, 2, 6, 3, 8, 3, 6, 7, 2, 2, 1, 9],
       [3, 3, 9, 5, 2, 4, 8, 5, 8, 1, 1, 6],
       [9, 2, 3, 6, 0, 3, 5, 8, 3, 6, 6, 7],
       [8, 4, 6, 5, 1, 1, 8, 5, 7, 6, 2, 7],
       [7, 2, 9, 7, 5, 3, 1, 0, 8, 5, 9, 1],
       [1, 4, 1, 5, 8, 5, 3, 6, 3, 7, 1, 1],
       [8, 2, 5, 2, 4, 9, 1, 2, 9, 9, 5, 5],
       [5, 3, 0, 0, 2, 5, 6, 1, 7, 6, 3, 5]])

In [102]:
#Añadir y eliminar elementos
np.append(array,34)

array([ 8,  2,  6,  3,  8,  3,  6,  7,  2,  2,  1,  9,  3,  3,  9,  5,  2,
        4,  8,  5,  8,  1,  1,  6,  9,  2,  3,  6,  0,  3,  5,  8,  3,  6,
        6,  7,  8,  4,  6,  5,  1,  1,  8,  5,  7,  6,  2,  7,  7,  2,  9,
        7,  5,  3,  1,  0,  8,  5,  9,  1,  1,  4,  1,  5,  8,  5,  3,  6,
        3,  7,  1,  1,  8,  2,  5,  2,  4,  9,  1,  2,  9,  9,  5,  5,  5,
        3,  0,  0,  2,  5,  6,  1,  7,  6,  3,  5, 34])

In [103]:
array=np.insert(array,2,99)
array

array([ 8,  2, 99,  6,  3,  8,  3,  6,  7,  2,  2,  1,  9,  3,  3,  9,  5,
        2,  4,  8,  5,  8,  1,  1,  6,  9,  2,  3,  6,  0,  3,  5,  8,  3,
        6,  6,  7,  8,  4,  6,  5,  1,  1,  8,  5,  7,  6,  2,  7,  7,  2,
        9,  7,  5,  3,  1,  0,  8,  5,  9,  1,  1,  4,  1,  5,  8,  5,  3,
        6,  3,  7,  1,  1,  8,  2,  5,  2,  4,  9,  1,  2,  9,  9,  5,  5,
        5,  3,  0,  0,  2,  5,  6,  1,  7,  6,  3,  5])

In [104]:
#Borrado
np.delete(array,[1])

array([ 8, 99,  6,  3,  8,  3,  6,  7,  2,  2,  1,  9,  3,  3,  9,  5,  2,
        4,  8,  5,  8,  1,  1,  6,  9,  2,  3,  6,  0,  3,  5,  8,  3,  6,
        6,  7,  8,  4,  6,  5,  1,  1,  8,  5,  7,  6,  2,  7,  7,  2,  9,
        7,  5,  3,  1,  0,  8,  5,  9,  1,  1,  4,  1,  5,  8,  5,  3,  6,
        3,  7,  1,  1,  8,  2,  5,  2,  4,  9,  1,  2,  9,  9,  5,  5,  5,
        3,  0,  0,  2,  5,  6,  1,  7,  6,  3,  5])

In [107]:
array_1 = np.random.randint(10, size=(4,4))
array_1

array([[5, 2, 8, 8],
       [6, 3, 2, 6],
       [1, 9, 2, 3],
       [8, 3, 8, 7]])

In [108]:
array_2 = np.random.randint(10, size=(4,4))
array_2

array([[3, 6, 8, 1],
       [1, 2, 0, 1],
       [0, 9, 4, 7],
       [2, 2, 7, 6]])

In [109]:
#Combinar arrays

In [111]:
array_combinado = np.concatenate((array_1,array_2), axis=0)
array_combinado

array([[5, 2, 8, 8],
       [6, 3, 2, 6],
       [1, 9, 2, 3],
       [8, 3, 8, 7],
       [3, 6, 8, 1],
       [1, 2, 0, 1],
       [0, 9, 4, 7],
       [2, 2, 7, 6]])

In [112]:
#Array vertica
array_combinado = np.vstack((array_1, array_2))
array_combinado

array([[5, 2, 8, 8],
       [6, 3, 2, 6],
       [1, 9, 2, 3],
       [8, 3, 8, 7],
       [3, 6, 8, 1],
       [1, 2, 0, 1],
       [0, 9, 4, 7],
       [2, 2, 7, 6]])

In [115]:
#otra forma array vertical
aray_combinado = np.r_[array_1,array_2]
array_combinado

array([[5, 2, 8, 8],
       [6, 3, 2, 6],
       [1, 9, 2, 3],
       [8, 3, 8, 7],
       [3, 6, 8, 1],
       [1, 2, 0, 1],
       [0, 9, 4, 7],
       [2, 2, 7, 6]])

In [116]:
#Combinado horizontal
array_combinado = np.hstack((array_1,array_2))
array_combinado

array([[5, 2, 8, 8, 3, 6, 8, 1],
       [6, 3, 2, 6, 1, 2, 0, 1],
       [1, 9, 2, 3, 0, 9, 4, 7],
       [8, 3, 8, 7, 2, 2, 7, 6]])

In [117]:
np.column_stack((array_1,array_2))

array([[5, 2, 8, 8, 3, 6, 8, 1],
       [6, 3, 2, 6, 1, 2, 0, 1],
       [1, 9, 2, 3, 0, 9, 4, 7],
       [8, 3, 8, 7, 2, 2, 7, 6]])

In [118]:
np.c_[array_1,array_2]

array([[5, 2, 8, 8, 3, 6, 8, 1],
       [6, 3, 2, 6, 1, 2, 0, 1],
       [1, 9, 2, 3, 0, 9, 4, 7],
       [8, 3, 8, 7, 2, 2, 7, 6]])

In [120]:
#Spliting, corte array vertical
np.vsplit(array_1, 2)

[array([[5, 2, 8, 8],
        [6, 3, 2, 6]]),
 array([[1, 9, 2, 3],
        [8, 3, 8, 7]])]

In [121]:
#Corte horizontal
np.hsplit(array_1, 2)

[array([[5, 2],
        [6, 3],
        [1, 9],
        [8, 3]]),
 array([[8, 8],
        [2, 6],
        [2, 3],
        [8, 7]])]