<a href="https://colab.research.google.com/github/jeo2k1/numpy/blob/main/Ejercicios_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejercicio1
Construir un array de 4 filas, segun se indica:
La primera fila estara formada por los numeros 6,7,9,15,22,34,
los elementos de la segunda fila equivalen a la fila anterior multiplicada por 2
la tercera fila equivalen a la fila anterior menos 5
la cuarta al cuadrado de la tercera fila.

In [2]:
import numpy as np

In [9]:
fila1=[6,7,9,15,22,34]
fila1

[6, 7, 9, 15, 22, 34]

In [8]:
fila2 =[2*x for x in fila1]
fila2

[12, 14, 18, 30, 44, 68]

In [11]:
fila3 = [x-5 for x in fila2]
fila3

[7, 9, 13, 25, 39, 63]

In [12]:
fila4 = [x**2 for x in fila3]
fila4

[49, 81, 169, 625, 1521, 3969]

In [16]:
array = np.array([fila1, fila2, fila3, fila4])
array

array([[   6,    7,    9,   15,   22,   34],
       [  12,   14,   18,   30,   44,   68],
       [   7,    9,   13,   25,   39,   63],
       [  49,   81,  169,  625, 1521, 3969]])

In [17]:
es_par = array[array % 2 == 0]
es_par

array([ 6, 22, 34, 12, 14, 18, 30, 44, 68])

#Ejercicio 2
 Resolver el siguiente sistema de ecuaciones, usando numpy

    x + 3y = 9

    6x + 3y = 5

In [27]:
ecuaciones = np.array([[1,3],[6,3]])
ecuaciones

array([[1, 3],
       [6, 3]])

In [28]:
resultados = np.array([9,5])
resultados

array([9, 5])

In [29]:
np.linalg.solve(ecuaciones,resultados)

array([-0.8       ,  3.26666667])