<a href="https://colab.research.google.com/github/jeo2k1/numpy/blob/main/Ejercicios_Varios_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Crea un array con elementos del 20 al 60 inclusives

In [3]:
array = np.arange(20,61,1)
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

Crea un array de una dimension con 15 elementos de unos, luego cambiar el tercer elemento a 99

In [7]:
array = np.ones((1,15))
array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
#cambiar el tercer elemento a 99
array[0,2] = 99
array

array([[ 1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.]])

Crea una matriz de 6 * 6 de ceros

In [6]:
array=np.zeros((6,6))
array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Convertir el tipo de datos anterior a entero





In [9]:
array.dtype

dtype('float64')

In [13]:
array.dtype = "int64"
array.dtype

dtype('int64')

Crea un array de numeros enteros del 1 al 20 inclusives, con 4 filas y 3 columnas, muestra el valor de la segunda fila y primera columna

In [20]:
array = np.random.randint(1,21,size=12).reshape(4,3)
array

array([[ 3,  6,  1],
       [ 7, 11,  9],
       [12,  8, 18],
       [20, 15, 10]])

In [21]:
array[1,0]

7

Crea un array con valores del rango 50 a 99 inclusives

In [18]:
array=np.arange(50,100)
array

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Invierte el array anterior

In [19]:
array[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50])

Crea una matriz 4 * 4 con valores de 1 a 16

In [25]:
array = np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Encontrar los valores mayores a 6 del array anterior

In [26]:
array_mayores = array[array>6]
array_mayores

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Crear una matriz identidad de 5 * 5

In [29]:
array = np.identity(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Crear matriz con valores al azar entre 0 y 1 de forma 4x4x4

In [31]:
array = np.random.random((4,4,4))
array

array([[[0.64469783, 0.7625178 , 0.12977939, 0.86967379],
        [0.61129534, 0.07645042, 0.55812223, 0.89201407],
        [0.87764232, 0.52427639, 0.43071176, 0.41253012],
        [0.14587877, 0.06591471, 0.4782607 , 0.42583511]],

       [[0.74763657, 0.29592202, 0.37700777, 0.87870757],
        [0.67330438, 0.26935893, 0.24903823, 0.62270118],
        [0.90529038, 0.1896575 , 0.02870178, 0.88162818],
        [0.48800118, 0.08495574, 0.39755896, 0.61460392]],

       [[0.3016756 , 0.26092806, 0.74141057, 0.77649722],
        [0.91055166, 0.95058419, 0.31756351, 0.39844846],
        [0.78686029, 0.27838956, 0.11854981, 0.9780671 ],
        [0.71408402, 0.54559107, 0.10899802, 0.56187053]],

       [[0.86993362, 0.66515571, 0.86171096, 0.53006327],
        [0.83423967, 0.15711846, 0.67995381, 0.90642547],
        [0.11857309, 0.90871077, 0.82481389, 0.85728938],
        [0.77587309, 0.99521107, 0.18048223, 0.92885045]]])

Indicar valor minimo y maximo del array anterior y su posicion


In [32]:
array.min()

0.028701776122205258

In [33]:
array.max()

0.995211069599962

Crear 2 arrays al azar y verificar si son iguales

In [35]:
array1=np.random.random((3,3))
array1

array([[0.55507885, 0.57123576, 0.84159246],
       [0.73068856, 0.45130158, 0.24341024],
       [0.53624963, 0.76860215, 0.2314813 ]])

In [36]:
array2=np.random.random((3,3))
array2

array([[0.23022764, 0.62601242, 0.80904067],
       [0.41977577, 0.57116856, 0.48580915],
       [0.33270219, 0.28721655, 0.34039366]])

In [38]:
array1 == array2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [39]:
np.array_equal(array1,array2)

False

De uno de los arrays anteriores obten la media y muestra los valores que estan por encima de la media

In [41]:
media = array1.mean()
media

0.5477378362097196

In [42]:
array1[array1 > media]


array([0.55507885, 0.57123576, 0.84159246, 0.73068856, 0.76860215])